name: eperusteet-pdf-service
on: [workflow_dispatch, push]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ARTIFACT_NAME: eperusteet-pdf

jobs:
  build-and-test-eperusteet-pdf-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build
        run: mvn clean verify -B
      - name: Upload eperusteet-pdf-service-jar
        uses: actions/upload-artifact@v3
        with:
          name: eperusteet-pdf-service-jar
          path: target/eperusteet-pdf-service.jar
  build-image:
    needs: [build-and-test-eperusteet-pdf-service]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Download eperusteet-pdf-service-jar
        uses: actions/download-artifact@v3
        with:
          name: eperusteet-pdf-service-jar
      - name: Build Docker Conainer
        shell: bash
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
          export BASE_IMAGE="baseimage-fatjar-openjdk11:master"
          echo "Current working directory is.."
          pwd
          echo "Current working directory content is.."
          ls -la
          cp eperusteet-pdf-service.jar $DOCKER_BUILD_DIR/artifact/eperusteet-pdf.jar
          echo "Generating some test content to config" >> $DOCKER_BUILD_DIR/config/testfile.txt
          echo "Contents of DOCKER_BUILD_DIR is.."
          ls -la "$DOCKER_BUILD_DIR"
          echo "Contents of DOCKER_BUILD_DIR/artifacts/.."
          ls -la "$DOCKER_BUILD_DIR"/artifact/
          echo "Contents of DOCKER_BUILD_DIR/config/.."
          ls -la "$DOCKER_BUILD_DIR"/config/
          echo "DOCKER_BUILD_DIR is.."
          echo "$DOCKER_BUILD_DIR"
          ./ci-tools/common/pull-image.sh
          ./ci-tools/github-build/build-fatjar.sh $ARTIFACT_NAME
          ./ci-tools/github-build/upload-image.sh $ARTIFACT_NAME